# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'DiseñoqNUjeU.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(973, 663)
        MainWindow.setStyleSheet(u"background-color: rgb(44, 62, 80);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 201, 31))
        font = QFont()
        font.setFamilies([u"Montserrat"])
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.txtFuncion = QLineEdit(self.centralwidget)
        self.txtFuncion.setObjectName(u"txtFuncion")
        self.txtFuncion.setGeometry(QRect(220, 20, 221, 31))
        self.txtFuncion.setFont(font)
        self.txtFuncion.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(236, 240, 241);\n"
"color: rgb(45, 45, 45);")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(130, 70, 91, 31))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(130, 120, 91, 31))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.txtH = QLineEdit(self.centralwidget)
        self.txtH.setObjectName(u"txtH")
        self.txtH.setGeometry(QRect(220, 70, 221, 31))
        self.txtH.setFont(font)
        self.txtH.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(236, 240, 241);\n"
"color: rgb(45, 45, 45);")
        self.txtX = QLineEdit(self.centralwidget)
        self.txtX.setObjectName(u"txtX")
        self.txtX.setGeometry(QRect(220, 120, 221, 31))
        self.txtX.setFont(font)
        self.txtX.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(236, 240, 241);\n"
"color: rgb(0, 0, 0);")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(400, 200, 91, 31))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(390, 400, 101, 31))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(390, 230, 101, 31))
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(370, 260, 121, 31))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(390, 300, 91, 31))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(370, 360, 121, 31))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(390, 330, 101, 31))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(380, 430, 111, 31))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(360, 460, 131, 31))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(380, 530, 111, 31))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(390, 500, 101, 31))
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(360, 560, 131, 31))
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(u"color: rgb(236, 240, 241);")
        self.tableWidget = QTableWidget(self.centralwidget)
        if (self.tableWidget.columnCount() < 2):
            self.tableWidget.setColumnCount(2)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font1);
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font1);
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(50, 190, 291, 411))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.tableWidget.setFont(font2)
        self.tableWidget.setStyleSheet(u"background-color: rgb(52, 73, 94);\n"
"border-color: rgb(236, 240, 241);")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(144)
        self.lblPrimeraDerivadaAtras = QLabel(self.centralwidget)
        self.lblPrimeraDerivadaAtras.setObjectName(u"lblPrimeraDerivadaAtras")
        self.lblPrimeraDerivadaAtras.setGeometry(QRect(490, 200, 521, 31))
        self.lblPrimeraDerivadaAtras.setFont(font)
        self.lblPrimeraDerivadaAtras.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblPrimeraDerivadaCentro = QLabel(self.centralwidget)
        self.lblPrimeraDerivadaCentro.setObjectName(u"lblPrimeraDerivadaCentro")
        self.lblPrimeraDerivadaCentro.setGeometry(QRect(490, 230, 521, 31))
        self.lblPrimeraDerivadaCentro.setFont(font)
        self.lblPrimeraDerivadaCentro.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblPrimeraDerivadaAdelante = QLabel(self.centralwidget)
        self.lblPrimeraDerivadaAdelante.setObjectName(u"lblPrimeraDerivadaAdelante")
        self.lblPrimeraDerivadaAdelante.setGeometry(QRect(490, 260, 521, 31))
        self.lblPrimeraDerivadaAdelante.setFont(font)
        self.lblPrimeraDerivadaAdelante.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblSegundaDerivadaAtras = QLabel(self.centralwidget)
        self.lblSegundaDerivadaAtras.setObjectName(u"lblSegundaDerivadaAtras")
        self.lblSegundaDerivadaAtras.setGeometry(QRect(490, 300, 521, 31))
        self.lblSegundaDerivadaAtras.setFont(font)
        self.lblSegundaDerivadaAtras.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblSegundaDerivadaCentro = QLabel(self.centralwidget)
        self.lblSegundaDerivadaCentro.setObjectName(u"lblSegundaDerivadaCentro")
        self.lblSegundaDerivadaCentro.setGeometry(QRect(490, 330, 521, 31))
        self.lblSegundaDerivadaCentro.setFont(font)
        self.lblSegundaDerivadaCentro.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblSegundaDerivadaAdelante = QLabel(self.centralwidget)
        self.lblSegundaDerivadaAdelante.setObjectName(u"lblSegundaDerivadaAdelante")
        self.lblSegundaDerivadaAdelante.setGeometry(QRect(490, 360, 521, 31))
        self.lblSegundaDerivadaAdelante.setFont(font)
        self.lblSegundaDerivadaAdelante.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblTerceraDerivadaAtras = QLabel(self.centralwidget)
        self.lblTerceraDerivadaAtras.setObjectName(u"lblTerceraDerivadaAtras")
        self.lblTerceraDerivadaAtras.setGeometry(QRect(490, 400, 521, 31))
        self.lblTerceraDerivadaAtras.setFont(font)
        self.lblTerceraDerivadaAtras.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblTerceraDerivadaCentro = QLabel(self.centralwidget)
        self.lblTerceraDerivadaCentro.setObjectName(u"lblTerceraDerivadaCentro")
        self.lblTerceraDerivadaCentro.setGeometry(QRect(490, 430, 521, 31))
        self.lblTerceraDerivadaCentro.setFont(font)
        self.lblTerceraDerivadaCentro.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblTerceraDerivadaAdelante = QLabel(self.centralwidget)
        self.lblTerceraDerivadaAdelante.setObjectName(u"lblTerceraDerivadaAdelante")
        self.lblTerceraDerivadaAdelante.setGeometry(QRect(490, 460, 521, 31))
        self.lblTerceraDerivadaAdelante.setFont(font)
        self.lblTerceraDerivadaAdelante.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblCuartaDerivadaAtras = QLabel(self.centralwidget)
        self.lblCuartaDerivadaAtras.setObjectName(u"lblCuartaDerivadaAtras")
        self.lblCuartaDerivadaAtras.setGeometry(QRect(490, 500, 521, 31))
        self.lblCuartaDerivadaAtras.setFont(font)
        self.lblCuartaDerivadaAtras.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblCuartaDerivadaCentro = QLabel(self.centralwidget)
        self.lblCuartaDerivadaCentro.setObjectName(u"lblCuartaDerivadaCentro")
        self.lblCuartaDerivadaCentro.setGeometry(QRect(490, 530, 521, 31))
        self.lblCuartaDerivadaCentro.setFont(font)
        self.lblCuartaDerivadaCentro.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.lblCuartaDerivadaAdelante = QLabel(self.centralwidget)
        self.lblCuartaDerivadaAdelante.setObjectName(u"lblCuartaDerivadaAdelante")
        self.lblCuartaDerivadaAdelante.setGeometry(QRect(490, 560, 521, 31))
        self.lblCuartaDerivadaAdelante.setFont(font)
        self.lblCuartaDerivadaAdelante.setStyleSheet(u"color: rgb(26, 188, 156);")
        self.btnCalcularDerivadas = QPushButton(self.centralwidget)
        self.btnCalcularDerivadas.setObjectName(u"btnCalcularDerivadas")
        self.btnCalcularDerivadas.setGeometry(QRect(520, 40, 151, 51))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.btnCalcularDerivadas.setFont(font3)
        self.btnCalcularDerivadas.setStyleSheet(u"background-color: rgb(39, 174, 96);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 973, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Ingrese la funci\u00f3n f<span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.txtFuncion.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Ingrese h:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Ingrese x:", None))
#if QT_CONFIG(tooltip)
        self.txtH.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.txtX.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Atras f'<span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Atras f<span style=\" vertical-align:super;\">(3)</span><span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Centro f'<span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Adelante f'<span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Atras f''<span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Adelante f''<span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Centro f''<span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Centro f<span style=\" vertical-align:super;\">(3)</span><span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Adelante f<span style=\" vertical-align:super;\">(3)</span><span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Centro f<span style=\" vertical-align:super;\">(4)</span><span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Atras f<span style=\" vertical-align:super;\">(4)</span><span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Adelante f<span style=\" vertical-align:super;\">(4)</span><span style=\" vertical-align:sub;\">(x)</span>:</p></body></html>", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"X\u1d62", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"f\u208d\u2093\u208e", None));
        self.lblPrimeraDerivadaAtras.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblPrimeraDerivadaCentro.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblPrimeraDerivadaAdelante.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblSegundaDerivadaAtras.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblSegundaDerivadaCentro.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblSegundaDerivadaAdelante.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblTerceraDerivadaAtras.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblTerceraDerivadaCentro.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblTerceraDerivadaAdelante.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblCuartaDerivadaAtras.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblCuartaDerivadaCentro.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.lblCuartaDerivadaAdelante.setText(QCoreApplication.translate("MainWindow", u"[Resultado]", None))
        self.btnCalcularDerivadas.setText(QCoreApplication.translate("MainWindow", u"Calcular derivadas", None))
    # retranslateUi

